@startuml

Usuario "1"-->"*" Parcela
RegistroClimatico "*"-->"1" Parcela
RegistroClimatico "*"-->"1..4" TipoPrecipitacion
RegistroRiego "*"-->"1" Parcela
RegistroPlantacion "*"-->"1" Parcela
RegistroPlantacion "*"-->"1" Cultivo
RegistroPlantacion "*"-->"1" EstadoRegistroPlantacion
RadiacionSolar "*"-->"1" Mes
RadiacionSolar "*"-->"1" Latitud
InsolacionMaxima "*"-->"1" Mes
InsolacionMaxima "*"-->"1" Latitud
Cultivo "*"-->"1" TipoCultivo
EnlaceActivacionCuenta "1" --> "1" Usuario
EnlaceRestablecimientoContraseña "*" --> "1" Usuario
Sesion "*" --> "1" Usuario
RegistroRiego "*" --> "1" Cultivo
Parcela "1" --> "1" Opcion
Cultivo "*" --> "0..1" Region
Cultivo "*" --> "0..2" Mes
Parcela "*" --> "0..1" Suelo
Contraseña "1" --> "1" Usuario
Parcela "1" --> "*" BalanceHidricoSuelo
Cosecha "*" --> "1" Parcela
Cosecha "*" --> "1" Cultivo
Parcela "1" --> "1" UbicacionGeografica

class Parcela {
-id
-nombre
-hectareas
-activa
-banderaUbicacionGeograficaModificada
}

class UbicacionGeografica {
-id
-latitud
-longitud
}

class Cosecha {
-id
-fecha
-cantidadCosecha
}

class Cultivo {
-id
-nombre
-etapaInicial
-etapaDesarrollo
-etapaMedia
-etapaFinal
-kcInicial
-kcMedio
-kcFinal
-cicloVida
-limiteInferiorProfundidadRadicularMaxima
-limiteSuperiorProfundidadRadicularMaxima
-fraccionAgotamientoHumedadSueloCultivo
-activo
}

class TipoCultivo {
-id
-nombre
-activo
}

class Region {
-id
-nombre
-activa
}

class RegistroClimatico {
-id
-fecha
-precipitacion
-probabilidadPrecipitacion
-puntoRocio
-presionAtmosferica
-velocidadViento
-nubosidad
-temperaturaMinima
-temperaturaMaxima
-eto
-etc
}

class TipoPrecipitacion {
-id
-nombre
-nombreEspañol
}

class RegistroPlantacion {
-id
-fechaSiembra
-fechaCosecha
-fechaMuerte
-necesidadAguaRiegoCultivo
-laminaTotalAguaDisponible
-laminaRiegoOptima
}

class RegistroRiego {
-id
-fecha
-riegoRealizado
}

class Opcion {
-id
-banderaSuelo
-banderaMensajeCapacidadCampo
}

class Usuario {
-id
-nombreUsuario
-nombre
-apellido
-email
-activo
-superUsuario
-modificadorSuperUsuario
}

class EstadoRegistroPlantacion {
-id
-nombre
-descripcion
}

class Mes {
-id
-nombre
}

class Latitud {
-id
-latitudDecimal
}

class RadiacionSolar {
-id
-valor
}

class InsolacionMaxima {
-id
-valor
}

class EnlaceActivacionCuenta {
-id
-fechaEmision
-fechaExpiracion
-consumido
}

class EnlaceRestablecimientoContraseña {
-id
-fechaEmision
-fechaExpiracion
-consumido
}

class Sesion {
-id
-fechaEmision
-fechaExpiracion
-cerrada
}

class ClaveSecreta {
-id
-valor
}

class BalanceHidricoSuelo {
-id
-fecha
-nombreParcela
-nombreCultivo
-aguaProvistaPorDia
-perdidaHumedadSueloPorDia
-deficitHumedadSueloPorDia
-acumuladoDeficitHumedadSueloPorDia
}

class Suelo {
-id
-nombre
-pesoEspecificoAparente
-capacidadCampo
-puntoMarchitezPermanente
-activo
}

class Contraseña {
-id
-valor
}

@enduml