@startuml

Parcela "*"-->"1" Usuario
InformeEstadistico "*"-->"1" Parcela
RegistroClimatico "*"-->"1" Parcela
RegistroClimatico "1"<-->"*" TipoPrecipitacion
RegistroRiego "*"-->"1" Parcela
RegistroPlantacion "*"-->"1" Parcela
RegistroPlantacion "*"-->"1" Cultivo
RegistroPlantacion "*"-->"1" EstadoRegistroPlantacion
RadiacionSolar "*"-->"1" Mes
RadiacionSolar "*"-->"1" Latitud
InsolacionMaxima "*"-->"1" Mes
InsolacionMaxima "*"-->"1" Latitud
Cultivo "*"-->"1" TipoCultivo
EnlaceActivacionCuenta "1" --> "1" Usuario
EnlaceRestablecimientoContraseña "*" --> "1" Usuario
Sesion "*" --> "1" Usuario
RegistroRiego "*" --> "1" Cultivo
Usuario "1" --> "1" Opcion
Cultivo "*" --> "1" Region
Cultivo "*" --> "2" Mes

class Parcela {
-id
-nombre
-hectareas
-latitud
-longitud
-activa
}

class InformeEstadistico {
-id
-fechaDesde
-fechaHasta
-cultivoMasPlantado
-cultivoMenosPlantado
-cultivoPlantadoMayorCicloVida
-cultivoPlantadoMenorCicloVida
-diasSinCultivoPlantado
-cantidadTotalAguaLluvia
}

class Cultivo {
-id
-nombre
-etapaInicial
-etapaDesarrollo
-etapaMedia
-etapaFinal
-kcInicial
-kcMedio
-kcFinal
-cicloVida
-activo
}

class TipoCultivo {
-id
-nombre
}

class Region {
-id
-nombre
}

class RegistroClimatico {
-id
-fecha
-precipitacion
-probabilidadPrecipitacion
-puntoRocio
-presionAtmosferica
-velocidadViento
-nubosidad
-temperaturaMinima
-temperaturaMaxima
-eto
-etc
}

class TipoPrecipitacion {
-id
-nombre
}

class RegistroPlantacion {
-id
-fechaSiembra
-fechaCosecha
-necesidadAguaRiego
}

class RegistroRiego {
-id
-fecha
-riegoRealizado
}

class Opcion {
-id
-diasPasadosReferencia
-banderaTreintaDias
}

class Usuario {
-id
-nombreUsuario
-contraseña
-nombre
-apellido
-email
-activo
-superUsuario
}

class EstadoRegistroPlantacion {
-id
-nombre
-descripcion
}

class Mes {
-id
-nombre
}

class Latitud {
-id
-latitudDecimal
}

class RadiacionSolar {
-id
-valor
}

class InsolacionMaxima {
-id
-valor
}

class EnlaceActivacionCuenta {
-id
-fechaEmision
-fechaExpiracion
-consumido
}

class EnlaceRestablecimientoContraseña {
-id
-fechaEmision
-fechaExpiracion
-consumido
}

class Sesion {
-id
-fechaEmision
-fechaExpiracion
-cerrada
}

class ClaveSecreta {
-id
-valor
}

@enduml