@startuml

Parcela "*"-->"1" Usuario
RegistroClimatico "*"-->"1" Parcela
RegistroRiego "*"-->"1" Parcela
RegistroPlantacion "*"-->"1" Parcela
RegistroPlantacion "*"-->"1" Cultivo
RegistroPlantacion "*"-->"1" EstadoRegistroPlantacion
RadiacionSolar "*"-->"1" Mes
RadiacionSolar "*"-->"1" Latitud
InsolacionMaxima "*"-->"1" Mes
InsolacionMaxima "*"-->"1" Latitud
Cultivo "*"-->"1" TipoCultivo
EnlaceActivacionCuenta "1" --> "1" Usuario
EnlaceRestablecimientoContraseña "*" --> "1" Usuario
Sesion "*" --> "1" Usuario
RegistroRiego "*" --> "1" Cultivo

class Parcela {
-id
-nombre
-hectarea
-latitud
-longitud
-activa
}

class Cultivo {
-id
-nombre
-etapaInicial
-etapaDesarrollo
-etapaMedia
-etapaFinal
-kcInicial
-kcMedio
-kcFinal
-cicloVida
-activo
}

class TipoCultivo {
-id
-nombre
}

class RegistroClimatico {
-id
-fecha
-precipitacion
-probabilidadPrecipitacion
-puntoRocio
-presionAtmosferica
-velocidadViento
-nubosidad
-temperaturaMinima
-temperaturaMaxima
-cantidadAguaAcumulada
-eto
-etc
}

class RegistroPlantacion {
-id
-fechaSiembra
-fechaCosecha
}

class RegistroRiego {
-id
-fecha
-riegoSugerido
-riegoRealizado
-precipitacionMañana
-generadoSistema
}

class Usuario {
-id
-nombreUsuario
-contraseña
-nombre
-apellido
-email
-activo
-superUsuario
}

class EstadoRegistroPlantacion {
-id
-nombre
-descripcion
}

class Mes {
-id
-nombre
}

class Latitud {
-id
-latitudDecimal
}

class RadiacionSolar {
-id
-valor
}

class InsolacionMaxima {
-id
-valor
}

class EnlaceActivacionCuenta {
-id
-fechaEmision
-fechaExpiracion
-consumido
}

class EnlaceRestablecimientoContraseña {
-id
-fechaEmision
-fechaExpiracion
-consumido
}

class Sesion {
-id
-fechaEmision
-fechaExpiracion
-cerrada
}

class ClaveSecreta {
-id
-valor
}

@enduml