-- A. HORTALIZAS PEQUEÑAS
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Brócoli', 35, 45, 40, 15, 135, 0.70, 1.05, 0.95, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Repollo', 40, 60, 50, 15, 165, 0.70, 1.05, 0.95, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Zanahoria', 20, 30, 50, 20, 120, 0.70, 1.05, 0.95, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Coliflor', 35, 50, 40, 15, 140, 0.70, 1.05, 0.95, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Apio', 25, 40, 95, 20, 180, 0.70, 1.05, 1.00, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Lechuga', 20, 30, 15, 10, 75, 0.70, 1.00, 0.95, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Cebolla seca', 20, 35, 110, 45, 210, 0.70, 1.05, 0.75, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Cebolla verde', 20, 45, 20, 10, 95, 0.70, 1.00, 1.00, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Espinaca', 20, 20, 25, 5, 70, 0.70, 1.00, 0.95, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Rábano', 5, 10, 15, 5, 35, 0.70, 0.90, 0.85, 1, 1);

-- B. HORTALIZAS - FAMILIA DE SOLANACEAS
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Berenjena', 30, 40, 40, 20, 130, 0.60, 1.05, 0.90, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Pimiento dulce', 30, 35, 40, 20, 125, 0.60, 1.05, 0.90, 1, 1);

-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada etapa fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Tomate', 30, 40, 45, 30, 145, 0.60, 1.15, 0.80, 1, 1);

-- C. HORTALIZAS - FAMILIA DE CURCUBITACEAS
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Pepino', 25, 35, 50, 20, 130, 0.60, 1.00, 0.75, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Calabacín (zucchini)', 25, 35, 25, 15, 100, 0.50, 0.95, 0.75, 1, 1);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Melón dulce', 25, 35, 40, 20, 120, 0.50, 1.05, 0.75, 1, 1);

-- D. TUBERCULOS
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Patata/Papa', 25, 30, 45, 30, 130, 0.50, 1.15, 0.75, 1, 2);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Remolacha azucarera', 25, 35, 50, 50, 160, 0.35, 1.20, 0.70, 1, 2);

-- E. LEGUMINOSAS
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Frijoles/Judías verdes', 20, 30, 30, 10, 90, 0.50, 1.05, 0.90, 1, 3);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Frijoles/Judías secas', 20, 30, 40, 20, 110, 0.4, 1.15, 0.35, 1, 3);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Maní', 25, 35, 45, 25, 130, 0.40, 1.15, 0.60, 1, 3);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Lentejas', 25, 35, 70, 40, 170, 0.40, 1.10, 0.30, 1, 3);

-- Estos datos fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Haba de soja', 15, 15, 40, 15, 85, 0.40, 1.15, 0.50, 1, 3);

-- F. HORTALIZAS PERENNES
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Alcachofa', 40, 40, 250, 30, 360, 0.50, 1.00, 0.95, 1, 4);

-- G. CULTIVOS TEXTILES
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Algodón', 30, 50, 60, 55, 195, 0.35, 1.20, 0.60, 1, 5);

-- H. CULTIVOS OLEAGINOSOS
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Girasol', 25, 35, 45, 25, 130, 0.35, 1.15, 0.35, 1, 6);

-- I. CEREALES
-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Cebada', 15, 25, 50, 30, 120, 0.30, 1.15, 0.25, 1, 7);

-- La duracion de cada etapa de este cultivo esta en el cuadro 11 del libro FAO 56, y sus coeficientes fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Granos pequeños', 25, 35, 65, 40, 165, 0.30, 1.10, 0.30, 1, 7);

-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Trigo de primavera', 30, 30, 40, 30, 130, 0.30, 1.15, 0.30, 1, 7);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Trigo de invierno con suelo congelado', 30, 140, 40, 30, 240, 0.40, 1.15, 0.25, 1, 7);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Trigo de invierno', 30, 140, 40, 30, 240, 0.70, 1.15, 0.25, 1, 7);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Maíz (grano)', 20, 35, 40, 30, 125, 0.70, 1.20, 0.35, 1, 7);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Maíz dulce', 20, 25, 25, 10, 80, 0.70, 1.15, 1.05, 1, 7);

-- La duracion de cada etapa de este cultivo esta en el cuadro 11 del libro FAO 56, y sus coeficientes fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Mijo', 15, 25, 40, 25, 105, 0.30, 1.00, 0.30, 1, 7);

-- La duracion de cada etapa de este cultivo esta en el cuadro 11 del libro FAO 56, y sus coeficientes fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Sorgo (grano)', 20, 35, 40, 30, 125, 0.30, 1.00, 0.55, 1, 7);

-- Estos datos estan en los cuadros 11 y 12 del libro FAO 56
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Arroz', 30, 30, 80, 40, 180, 1.05, 1.20, 0.90, 1, 7);

-- J. FORRAJES
-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Alfalfa', 150, 30, 150, 35, 365, 0.40, 0.95, 0.90, 1, 8);

-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Césped frío', 150, 40, 130, 45, 365, 0.90, 0.95, 0.95, 1, 8);

-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Césped caliente', 150, 50, 125, 40, 365, 0.80, 0.85, 0.85, 1, 8);

-- Este cultivo y sus datos fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Pasto perenne', 140, 60, 120, 45, 365, 0.85, 0.95, 0.85, 1, 8);

-- K. CAÑA DE AZUCAR
-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Caña de azucar', 30, 60, 180, 95, 365, 0.40, 1.25, 0.75, 1, 9);

-- L. FRUTAS TROPICALES Y ARBOLES
-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Banana', 90, 165, 45, 30, 330, 0.50, 1.10, 1.0, 1, 10);

-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Palmera datilera', 140, 30, 150, 45, 365, 0.90, 0.95, 0.95, 1, 11);

-- M. UVAS
-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Uvas de mesa', 150, 50, 125, 40, 365, 0.30, 0.85, 0.45, 1, 12);

-- Los coeficientes de este cultivo estan en el cuadro 12 del libro FAO 56, y el dato de lo que dura cada una de sus etapas fue tomado de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Uvas de vino', 150, 50, 125, 40, 365, 0.30, 0.70, 0.45, 1, 12);

-- N. CULTIVOS TRADICIONALES TROPICALES
-- Estos datos fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Tabaco', 20, 30, 30, 30, 110, 0.50, 1.15, 0.80, 1, 13);

-- Los datos de este cultivo fueron tomados de un archivo .CRO
INSERT INTO CROP (NAME, INITIAL_STAGE, DEVELOPMENT_STAGE, MIDDLE_STAGE, FINAL_STAGE, LIFE_CYCLE, INITIAL_KC, MIDDLE_KC, FINAL_KC, ACTIVE, FK_TYPE_CROP)
VALUES ('Mango', 90, 90, 90, 95, 365, 0.90, 1.10, 0.90, 1, 13);