-- DELETES
DELETE FROM MAXIMUM_INSOLATION;
ALTER TABLE MAXIMUM_INSOLATION ALTER COLUMN MAXIMUM_INSOLATION_ID RESTART WITH 1;

DELETE FROM SOLAR_RADIATION;
ALTER TABLE SOLAR_RADIATION ALTER COLUMN SOLAR_RADIATION_ID RESTART WITH 1;

DELETE FROM LATITUDE;
ALTER TABLE LATITUDE ALTER COLUMN LATITUDE_ID RESTART WITH 1;

DELETE FROM MONTH;
ALTER TABLE MONTH ALTER COLUMN MONTH_ID RESTART WITH 1;

DELETE FROM IRRIGATION_LOG;
ALTER TABLE IRRIGATION_LOG ALTER COLUMN IRRIGATION_LOG_ID RESTART WITH 1;

DELETE FROM CLIMATE_RECORD;
ALTER TABLE CLIMATE_RECORD ALTER COLUMN ID RESTART WITH 1;

DELETE FROM PLANTING_RECORD;
ALTER TABLE PLANTING_RECORD ALTER COLUMN ID RESTART WITH 1;

DELETE FROM CROP;
ALTER TABLE CROP ALTER COLUMN ID RESTART WITH 1;

DELETE FROM PARCEL;
ALTER TABLE PARCEL ALTER COLUMN ID RESTART WITH 1;

DELETE FROM IRRIGATION_SYSTEM_USER;
ALTER TABLE IRRIGATION_SYSTEM_USER ALTER COLUMN ID RESTART WITH 1;
