-- DELETES
DELETE FROM MAXIMUM_INSOLATION;
ALTER TABLE MAXIMUM_INSOLATION ALTER COLUMN MAXIMUM_INSOLATION_ID RESTART WITH 1;

DELETE FROM SOLAR_RADIATION;
ALTER TABLE SOLAR_RADIATION ALTER COLUMN SOLAR_RADIATION_ID RESTART WITH 1;

DELETE FROM LATITUDE;
ALTER TABLE LATITUDE ALTER COLUMN LATITUDE_ID RESTART WITH 1;

DELETE FROM MONTH;
ALTER TABLE MONTH ALTER COLUMN MONTH_ID RESTART WITH 1;

DELETE FROM IRRIGATION_LOG;
ALTER TABLE IRRIGATION_LOG ALTER COLUMN IRRIGATION_LOG_ID RESTART WITH 1;

DELETE FROM CLIMATE_LOG;
ALTER TABLE CLIMATE_LOG ALTER COLUMN CLIMATE_LOG_ID RESTART WITH 1;

DELETE FROM INSTANCIA_PARCELA;
ALTER TABLE INSTANCIA_PARCELA ALTER COLUMN INSTANCIA_PARCELA_ID RESTART WITH 1;

DELETE FROM CULTIVO;
ALTER TABLE CULTIVO ALTER COLUMN CULTIVO_ID RESTART WITH 1;

DELETE FROM PARCEL;
ALTER TABLE PARCEL ALTER COLUMN PARCEL_ID RESTART WITH 1;

DELETE FROM USUARIO;
ALTER TABLE USUARIO ALTER COLUMN USUARIO_ID RESTART WITH 1;
