INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.0, '0.0', 1, 0, 1, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.2, '0.0', 0, 1, 1, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.1, '0.0', 0, 1, 1, 1);

INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.0, '0.0', 1, 0, 3, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.2, '0.0', 0, 1, 3, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.1, '0.0', 0, 1, 3, 1);

INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.0, '0.0', 1, 0, 5, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 2.2, '0.0', 0, 1, 5, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 5, 1);

-- Este conjunto de datos es para probar el correcto funcionamiento del metodo automatico unsetModifiable de la clase IrrigationRecordManager
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 0.0, '0.0', 1, 0, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 2.2, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 1.5, '0.0', 1, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 2.2, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 6, 1);
INSERT INTO IRRIGATION_RECORD ("DATE", IRRIGATION_DONE, IRRIGATION_WATER_NEED, SYSTEM_GENERATED, MODIFIABLE, FK_PARCEL, FK_CROP)
VALUES ('2019-11-13', 3.1, '0.0', 0, 1, 6, 1);
