-- DELETE
DELETE FROM IRRIGATION_LOG;
ALTER TABLE IRRIGATION_LOG ALTER COLUMN IRRIGATION_LOG_ID RESTART WITH 1;

-- INSERTS
INSERT INTO IRRIGATION_LOG (DATE, IRRIGATION_DONE, SUGGESTED_IRRIGATION, FK_PARCEL) VALUES ('2019-11-13', 0.5, 0.0, 1);
INSERT INTO IRRIGATION_LOG (DATE, IRRIGATION_DONE, SUGGESTED_IRRIGATION, FK_PARCEL) VALUES ('2019-11-13', 0.2, 0.0, 1);
INSERT INTO IRRIGATION_LOG (DATE, IRRIGATION_DONE, SUGGESTED_IRRIGATION, FK_PARCEL) VALUES ('2019-11-13', 0.1, 0.0, 1);

INSERT INTO IRRIGATION_LOG (DATE, IRRIGATION_DONE, SUGGESTED_IRRIGATION, FK_PARCEL) VALUES ('2019-11-13', 1.5, 0.0, 2);
INSERT INTO IRRIGATION_LOG (DATE, IRRIGATION_DONE, SUGGESTED_IRRIGATION, FK_PARCEL) VALUES ('2019-11-13', 2.2, 0.0, 2);
INSERT INTO IRRIGATION_LOG (DATE, IRRIGATION_DONE, SUGGESTED_IRRIGATION, FK_PARCEL) VALUES ('2019-11-13', 3.1, 0.0, 2);
