INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);