-- DELETE
DELETE FROM PARCEL_INSTANCE;
ALTER TABLE PARCEL_INSTANCE ALTER COLUMN PARCEL_INSTANCE_ID RESTART WITH 1;

-- INSERTS
INSERT INTO PARCEL_INSTANCE (SEED_DATE, FK_PARCEL, FK_CROP) VALUES ('2019-10-1', 1, 1);
INSERT INTO PARCEL_INSTANCE (SEED_DATE, HARVEST_DATE, FK_PARCEL, FK_CROP) VALUES ('2019-10-1', '2019-10-11', 2, 2);
