INSERT INTO PAST_DAYS_REFERENCE ("VALUE", FK_USER) VALUES (1, 1);
INSERT INTO PAST_DAYS_REFERENCE ("VALUE", FK_USER) VALUES (3, 2);
INSERT INTO PAST_DAYS_REFERENCE ("VALUE", FK_USER) VALUES (3, 3);
INSERT INTO PAST_DAYS_REFERENCE ("VALUE", FK_USER) VALUES (4, 4);
INSERT INTO PAST_DAYS_REFERENCE ("VALUE", FK_USER) VALUES (5, 5);
INSERT INTO PAST_DAYS_REFERENCE ("VALUE", FK_USER) VALUES (6, 6);