INSERT INTO SOIL ("NAME", APPARENT_SPECIFIC_WEIGHT, FIELD_CAPACITY, PERMANENT_WILTING, ACTIVE) VALUES ('Arenoso', 1.65, 9, 4, 1);
INSERT INTO SOIL ("NAME", APPARENT_SPECIFIC_WEIGHT, FIELD_CAPACITY, PERMANENT_WILTING, ACTIVE) VALUES ('Franco arenoso', 1.50, 14, 6, 1);
INSERT INTO SOIL ("NAME", APPARENT_SPECIFIC_WEIGHT, FIELD_CAPACITY, PERMANENT_WILTING, ACTIVE) VALUES ('Franco', 1.4, 22, 10, 1);
INSERT INTO SOIL ("NAME", APPARENT_SPECIFIC_WEIGHT, FIELD_CAPACITY, PERMANENT_WILTING, ACTIVE) VALUES ('Franco arcilloso', 1.35, 27, 13, 1);
INSERT INTO SOIL ("NAME", APPARENT_SPECIFIC_WEIGHT, FIELD_CAPACITY, PERMANENT_WILTING, ACTIVE) VALUES ('Arcilloso limoso', 1.3, 31, 15, 1);
INSERT INTO SOIL ("NAME", APPARENT_SPECIFIC_WEIGHT, FIELD_CAPACITY, PERMANENT_WILTING, ACTIVE) VALUES ('Arcilloso', 1.25, 35, 17, 1);