INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (1, 'Cantidad total de plantaciones por cultivo');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (2, 'Cantidad total de plantaciones por cultivo y año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (3, 'Cantidad total de agua de riego por cultivo');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (4, 'Cantidad total de agua de riego por cultivo y año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (5, 'Cantidad total cosechada por cultivo');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (6, 'Cantidad total cosechada por cultivo y año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (7, 'Cantidad total de plantaciones por tipo de cultivo');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (8, 'Cantidad total de plantaciones por tipo de cultivo y año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (9, 'Cantidad total de agua de riego por tipo de cultivo');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (10, 'Cantidad total de agua de riego por tipo de cultivo y año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (11, 'Cantidad total cosechada por tipo de cultivo');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (12, 'Cantidad total cosechada por tipo de cultivo y año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (13, 'Ciclos de vida de los cultivos sembrados');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (14, 'Cantidad total de agua de riego de cultivo por año');
INSERT INTO STATISTICAL_DATA (NUMBER, DESCRIPTION) VALUES (15, 'Cantidad total de agua de lluvia por año');