INSERT INTO STATISTICAL_REPORT (CROP_LONGEST_LIFE_CYCLE_PLANTED, CROP_SHORTEST_LIFE_CYCLE_PLANTED, DATE_FROM, DATE_UNTIL, DAYS_WITHOUT_CROPS, LESS_PLANTED_CROP, MOST_PLANTED_CROP, TOTAL_AMOUNT_RAINWATER, FK_PARCEL)
VALUES ('Cebolla seca', 'Rábano', '2023-01-01', '2030-02-09', '327', 'Rábano', 'Tomate', '30.0', 1);
INSERT INTO STATISTICAL_REPORT (CROP_LONGEST_LIFE_CYCLE_PLANTED, CROP_SHORTEST_LIFE_CYCLE_PLANTED, DATE_FROM, DATE_UNTIL, DAYS_WITHOUT_CROPS, LESS_PLANTED_CROP, MOST_PLANTED_CROP, TOTAL_AMOUNT_RAINWATER, FK_PARCEL)
VALUES ('Cebolla verde', 'Zanahoria', '2022-01-01', '2027-01-01', '211', 'Alfalfa', 'Lechuga', '2.0', 1);
INSERT INTO STATISTICAL_REPORT (CROP_LONGEST_LIFE_CYCLE_PLANTED, CROP_SHORTEST_LIFE_CYCLE_PLANTED, DATE_FROM, DATE_UNTIL, DAYS_WITHOUT_CROPS, LESS_PLANTED_CROP, MOST_PLANTED_CROP, TOTAL_AMOUNT_RAINWATER, FK_PARCEL)
VALUES ('Alcachofa', 'Uvas de mesa', '2021-05-01', '2023-05-12', '140', 'Uvas de vino', 'Apio', '4.0', 1);

INSERT INTO STATISTICAL_REPORT (CROP_LONGEST_LIFE_CYCLE_PLANTED, CROP_SHORTEST_LIFE_CYCLE_PLANTED, DATE_FROM, DATE_UNTIL, DAYS_WITHOUT_CROPS, LESS_PLANTED_CROP, MOST_PLANTED_CROP, TOTAL_AMOUNT_RAINWATER, FK_PARCEL)
VALUES ('Pimiento dulce', 'Apio', '2021-12-01', '2022-02-19', '90', 'Rábano', 'Coliflor', '20.0', 2);
INSERT INTO STATISTICAL_REPORT (CROP_LONGEST_LIFE_CYCLE_PLANTED, CROP_SHORTEST_LIFE_CYCLE_PLANTED, DATE_FROM, DATE_UNTIL, DAYS_WITHOUT_CROPS, LESS_PLANTED_CROP, MOST_PLANTED_CROP, TOTAL_AMOUNT_RAINWATER, FK_PARCEL)
VALUES ('Pepino', 'Calabacín (zucchini)', '2022-05-21', '2024-05-12', '100', 'Patata/Papa', 'Berenjena', '25.0', 2);
INSERT INTO STATISTICAL_REPORT (CROP_LONGEST_LIFE_CYCLE_PLANTED, CROP_SHORTEST_LIFE_CYCLE_PLANTED, DATE_FROM, DATE_UNTIL, DAYS_WITHOUT_CROPS, LESS_PLANTED_CROP, MOST_PLANTED_CROP, TOTAL_AMOUNT_RAINWATER, FK_PARCEL)
VALUES ('Maní', 'Lentejas', '2022-09-09', '2023-02-24', '190', 'Tomate', 'Rábano', '15.0', 2);