-- Este archivo corresponde a la tarea 89 de la pila del producto.
-- LEER: Este conjunto de datos es para la prueba del modulo automatico ExpiredAccountManager, el cual, se encuentra en la ruta app/src/accountsAdministration.
-- Este modulo automatico elimina los enlaces de activacion de cuenta expirados y NO consumidos, y las cuentas registradas asociadas a los mismos.

INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);
INSERT INTO USER_OPTION (PAST_DAYS_REFERENCE, THIRTY_DAYS_FLAG) VALUES (7, 0);

INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('gdelf0', 'VODGzq9LW', 'Goddart', 'Delf', 'ktaunton0@hexun.com', 1, 0, 1);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('emarc1', 'agqHcBhE', 'Edik', 'Marc', 'jrichardes2@nsw.gov.au', 1, 0, 2);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('belderkin2', 'xiMBgK', 'Bobbye', 'Elderkin', 'jcurbishley1@hc360.com', 0, 0, 3);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('pporte3', 'PX0VKwBDj1', 'Pippo', 'Porte', 'kdesaur3@accuweather.com', 0, 0, 4);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('csummerill4', 'XwjKbN9ld0', 'Corilla', 'Summerill', 'bhuc4@yolasite.com', 0, 0, 5);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('cbranford5', 'KMROj1KshcR', 'Cthrine', 'Branford', 'jwallbrook5@altervista.org', 0, 0, 6);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('ogrishkov6', 'nRdNTZ4P3', 'Ole', 'Grishkov', 'cwestell6@prweb.com', 0, 0, 7);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('cbaumber7', 'zOUlxtCuLRj', 'Cyrille', 'Baumber', 'biddens7@hhs.gov', 0, 0, 8);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('gfrapwell8', 'yZSbZhVVcOE', 'Gaven', 'Frapwell', 'hcoger8@alexa.com', 0, 0, 9);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('hcrummie9', 'VcNEykQP', 'Harriott', 'Crummie', 'hpeasgood9@4shared.com', 0, 0, 10);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('bbaumforda', 'I5hbW8jv', 'Bernhard', 'Baumford', 'afreshwatera@biblegateway.com', 0, 0, 11);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('nwithamsb', 'l24wb5', 'Nanine', 'Withams', 'aharmesb@t-online.de', 0, 0, 12);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('cstellic', 'g9NARf', 'Cathy', 'Stelli', 'edebrettc@nationalgeographic.com', 0, 0, 13);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('lwallingd', 'qnjcNeBI', 'Lou', 'Walling', 'cmcardled@newyorker.com', 0, 0, 14);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('hmcquiltye', 'Mzfp8EVQ9', 'Hewie', 'McQuilty', 'pstennese@digg.com', 0, 0, 15);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('adightf', 'HwCqgA2r2', 'Aeriela', 'Dight', 'rstihlf@irs.gov', 0, 0, 16);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('kmcgraffing', '6o58t3dZoy29', 'Katlin', 'McGraffin', 'poverg@dedecms.com', 0, 0, 17);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('bbeddowsh', 'UHyPwomlQ', 'Booth', 'Beddows', 'tseymarkh@loc.gov', 0, 0, 18);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('cgorettii', '1ztuMWkr', 'Carlyn', 'Goretti', 'fouthwaitei@kickstarter.com', 0, 0, 19);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('jpauelj', 'Hfs61O7', 'Jennine', 'Pauel', 'rmolnarj@wsj.com', 0, 0, 20);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('ccolebeckk', 'iSEGIulCkax', 'Crystie', 'Colebeck', 'cvarnek@ca.gov', 0, 0, 21);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('pcalderbankl', 'QTFOS78Cq', 'Paul', 'Calderbank', 'tberryl@behance.net', 0, 0, 22);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('jtulipm', 'h4im6EsqY4', 'Johann', 'Tulip', 'hfredam@examiner.com', 0, 0, 23);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('dmatselln', '086hJGbnE7dM', 'Derek', 'Matsell', 'cbullern@jimdo.com', 0, 0, 24);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, NAME, LAST_NAME, EMAIL, ACTIVE, SUPERUSER, FK_OPTION)
VALUES ('nclemmeyo', '0tzukl', 'Nilson', 'Clemmey', 'frizzardoo@jalbum.net', 0, 0, 25);

INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-12-09 00:00:00', '2022-10-14 00:00:00', 1, 1);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-03-24 00:00:00', '2022-11-27 00:00:00', 1, 2);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-11-23 00:00:00', '2022-03-20 00:00:00', 0, 3);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-03-20 00:00:00', '2022-06-21 00:00:00', 0, 4);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-02-22 00:00:00', '2022-12-01 00:00:00', 0, 5);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-03-10 00:00:00', '2022-08-06 00:00:00', 0, 6);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-09-14 00:00:00', '2022-01-26 00:00:00', 0, 7);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-09-05 00:00:00', '2022-04-29 00:00:00', 0, 8);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-08-31 00:00:00', '2022-08-18 00:00:00', 0, 9);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-04-14 00:00:00', '2022-01-30 00:00:00', 0, 10);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-06-01 00:00:00', '2022-07-28 00:00:00', 0, 11);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-03-13 00:00:00', '2022-01-15 00:00:00', 0, 12);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-12-09 00:00:00', '2022-10-04 00:00:00', 0, 13);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-06-13 00:00:00', '2022-01-22 00:00:00', 0, 14);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-08-29 00:00:00', '2022-02-01 00:00:00', 0, 15);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-02-06 00:00:00', '2022-02-25 00:00:00', 0, 16);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-02-13 00:00:00', '2022-09-11 00:00:00', 0, 17);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-01-13 00:00:00', '2022-06-10 00:00:00', 0, 18);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-04-30 00:00:00', '2022-12-02 00:00:00', 0, 19);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-04-16 00:00:00', '2022-07-11 00:00:00', 0, 20);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-11-25 00:00:00', '2022-09-30 00:00:00', 0, 21);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-11-20 00:00:00', '2022-03-23 00:00:00', 0, 22);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-01-11 00:00:00', '2022-08-14 00:00:00', 0, 23);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-04-24 00:00:00', '2022-05-19 00:00:00', 0, 24);
INSERT INTO ACCOUNT_ACTIVATION_LINK (DATE_ISSUE, EXPIRATION_DATE, CONSUMED, FK_USER) VALUES ('2022-06-05 00:00:00', '2022-12-31 00:00:00', 0, 25);