INSERT INTO TYPE_PRECIPITATION (NAME, SPANISH_NAME) VALUES ('rain', 'Lluvia');
INSERT INTO TYPE_PRECIPITATION (NAME, SPANISH_NAME) VALUES ('ice', 'Granizo');
INSERT INTO TYPE_PRECIPITATION (NAME, SPANISH_NAME) VALUES ('snow', 'Nieve');
INSERT INTO TYPE_PRECIPITATION (NAME, SPANISH_NAME) VALUES ('freezing rain', 'Lluvia gélida');